language: java
jdk:
  - oraclejdk8
notifications:
  email: false
  irc:
    channels:
    - "irc.stealth.net#tetrisjavalabra"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
    - '#%{build_number} %{message} (%{branch} : %{author}): %{commit_message}'

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - mvn clean test jacoco:report coveralls:report
